"use client";

import { useMemo, useState } from "react";
import { CareFlowError, EXAMPLE_PROGRAMS, interpret, lex, parse, validate } from "@/lib/careflow";

type Tab="SOURCE"|"TOKENS"|"AST"|"EXECUTION RESULT";
const tabs:Tab[]=["SOURCE","TOKENS","AST","EXECUTION RESULT"];

export function LanguageExplorer(){
  const [source,setSource]=useState(EXAMPLE_PROGRAMS[0]!.source);
  const [tab,setTab]=useState<Tab>("SOURCE");
  const analysis=useMemo(()=>{try{const tokens=lex(source);const ast=parse(source);const validation=validate(ast);const result=interpret(ast,{oxygen:87,heart_rate:82});return{tokens,ast,validation,result,error:null};}catch(error){return{tokens:null,ast:null,validation:null,result:null,error:error instanceof CareFlowError?{name:error.name,message:error.message,line:error.loc.line,column:error.loc.column}:String(error)};}},[source]);
  const output=tab==="TOKENS"?analysis.tokens:tab==="AST"?analysis.ast:tab==="EXECUTION RESULT"?{validation:analysis.validation,execution:analysis.result}:null;
  return <div className="mx-auto max-w-[1500px] px-5 py-10 lg:px-8"><div className="mb-8 max-w-3xl"><p className="eyebrow mb-3">Language Explorer</p><h1 className="text-3xl font-bold tracking-tight">Inspect a real programming-language pipeline</h1><p className="mt-3 text-base leading-7 text-[#62716d]">Edit source and inspect the exact tokens, typed AST, semantic diagnostics, and snapshot execution returned by the CareFlow engine.</p></div>
    <div className="mb-8 grid gap-2 md:grid-cols-7">{[["01","Tokens","Lexer"],["02","Syntax tree","Parser"],["03","Typed nodes","AST"],["04","Safety checks","Validator"],["05","Rule state","Interpreter"],["06","Time series","Runtime"],["07","Audit trail","Trace"]].map(([n,title,sub])=><div key={n} className="panel p-3"><span className="font-mono text-[10px] text-[#087f72]">{n}</span><b className="mt-3 block text-xs">{title}</b><span className="mt-1 block text-[10px] uppercase tracking-wide text-[#84938f]">{sub}</span></div>)}</div>
    <div className="panel overflow-hidden"><div className="flex overflow-x-auto border-b border-[#dce5e2] bg-[#f7f9f8] px-2">{tabs.map((item)=><button key={item} onClick={()=>setTab(item)} className={`border-b-2 px-4 py-3 text-[11px] font-bold tracking-wider ${tab===item?"border-[#087f72] text-[#076a60]":"border-transparent text-[#71807c]"}`}>{item}</button>)}<div className="ml-auto hidden items-center pr-3 text-[10px] font-bold text-[#71807c] md:flex"><span className={`status-dot mr-2 ${analysis.error?"bg-[#c94b4b]":"bg-[#18a38f]"}`}/>{analysis.error?"PIPELINE ERROR":"PIPELINE COMPLETE"}</div></div>
      {tab==="SOURCE"?<div className="grid lg:grid-cols-[1fr_340px]"><textarea aria-label="Language explorer source" spellCheck={false} value={source} onChange={(e)=>setSource(e.target.value)} className="code-scroll h-[620px] resize-none bg-[#13201e] p-5 font-mono text-[13px] leading-6 text-[#d7e7e3] outline-none"/><aside className="border-l border-[#dce5e2] p-5"><span className="eyebrow">Live analysis</span>{analysis.error?<div className="mt-4 rounded-lg border border-[#ecc4c4] bg-[#fff5f5] p-3 text-xs leading-5 text-[#a83333]"><b>{typeof analysis.error==="object"&&"name" in analysis.error?analysis.error.name:"Error"}</b><pre className="mt-2 whitespace-pre-wrap font-mono">{JSON.stringify(analysis.error,null,2)}</pre></div>:<><div className="mt-4 grid grid-cols-2 gap-2"><Metric value={analysis.tokens!.length} label="Tokens"/><Metric value={analysis.ast!.rules.length} label="Rules"/><Metric value={analysis.ast!.monitors.length} label="Monitors"/><Metric value={analysis.validation!.diagnostics.length} label="Diagnostics"/></div><p className="mt-5 text-xs leading-6 text-[#61716c]">Nothing on this page is precomputed. Each keystroke invokes the lexer, parser, AST construction, semantic validator, and snapshot interpreter.</p></>}</aside></div>:<pre className="code-scroll h-[620px] overflow-auto bg-[#13201e] p-5 font-mono text-xs leading-6 text-[#d7e7e3]">{analysis.error?JSON.stringify(analysis.error,null,2):JSON.stringify(output,null,2)}</pre>}
    </div>
    <div className="mt-5 rounded-lg border border-[#e2c989] bg-[#fffaf0] px-4 py-3 text-xs text-[#73551a]"><b>Hackathon language demonstration.</b> Programs and readings are synthetic and provide no clinical guidance.</div>
  </div>;
}
function Metric({value,label}:{value:number;label:string}){return <div className="rounded-lg border border-[#dce5e2] bg-[#f8faf9] p-3"><b className="font-mono text-xl text-[#087f72]">{value}</b><span className="mt-1 block text-[10px] font-bold uppercase tracking-wider text-[#71807c]">{label}</span></div>;}
