import Link from "next/link";
import { EXAMPLE_PROGRAMS } from "@/lib/careflow";

const pipeline = ["Visual Builder","CareFlow DSL","Lexer","Parser","Typed AST","Validator","Stateful Interpreter","Execution Trace"];
const icons = ["O₂","♥","LAB","LINK"];

export default function Overview() {
  return <div className="mx-auto max-w-[1500px] px-5 py-10 lg:px-8 lg:py-14">
    <section className="grid gap-10 border-b border-[#dce5e2] pb-12 lg:grid-cols-[1.2fr_.8fr] lg:items-center">
      <div><p className="eyebrow mb-4">Operational incident coordination</p><h1 className="max-w-3xl text-4xl font-bold leading-[1.08] tracking-[-.035em] text-[#14211f] lg:text-6xl">Route the alert.<br/><span className="text-[#087f72]">Track the response.</span><br/>Audit the escalation.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#5d6d69]">Hospital teams often coordinate time-sensitive operational alerts across disconnected tools and manual handoffs. CareFlow Studio is an MVP for designing and simulating clear assignment, acknowledgement, and escalation workflows.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/simulator?demo=ventilator" className="rounded-lg bg-[#087f72] px-5 py-3 text-sm font-bold text-white no-underline hover:bg-[#076a60]">▶ Run ER Ventilator Demo</Link><Link href="/studio?example=device_alert" className="rounded-lg border border-[#cdd9d6] bg-white px-5 py-3 text-sm font-bold text-[#263633] no-underline hover:border-[#87bdb4]">Open workflow in Studio</Link></div></div>
      <div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-[#dce5e2] px-5 py-3"><span className="text-xs font-bold uppercase tracking-wider text-[#64736f]">Compiler pipeline</span><span className="rounded-full bg-[#e7f5f2] px-2.5 py-1 text-[10px] font-bold text-[#087f72]">REAL ENGINE</span></div><div className="p-5">{pipeline.map((item,index)=><div key={item} className="flex flex-col items-center"><div className={`w-full rounded-lg border px-4 py-2.5 text-center text-sm font-bold ${index===1?"border-[#72bcb0] bg-[#e7f5f2] text-[#076a60]":index>4?"border-[#bfd1e1] bg-[#f3f7fb] text-[#285b8b]":"border-[#dce5e2] bg-[#fafcfb] text-[#344541]"}`}>{item}</div>{index<pipeline.length-1&&<span className="py-1 text-[#8ba09b]">↓</span>}</div>)}</div></div>
    </section>

    <section className="grid gap-4 border-b border-[#dce5e2] py-12 md:grid-cols-3"><div className="panel p-5"><p className="eyebrow mb-3">The problem</p><h2 className="text-lg font-bold">Operational ownership can be unclear</h2><p className="mt-2 text-sm leading-6 text-[#687873]">Alerts need an accountable team, a visible response deadline, and a consistent escalation trail.</p></div><div className="panel p-5"><p className="eyebrow mb-3">Current MVP</p><h2 className="text-lg font-bold">Executable simulation and audit</h2><p className="mt-2 text-sm leading-6 text-[#687873]">Hospital operations, clinical engineering, digital health, quality, healthcare cybersecurity, and emergency-preparedness teams can test synthetic workflows before any integration.</p></div><div className="panel p-5"><p className="eyebrow mb-3">Planned progression</p><h2 className="text-lg font-bold">Simulation → planned read-only integration</h2><p className="mt-2 text-sm leading-6 text-[#687873]">Future, planned read-only integrations could receive approved events from device-management, network-monitoring, or security systems. They are not currently implemented; this MVP has no live connections and sends no device commands.</p></div></section>

    <section className="py-12"><div className="mb-6 flex items-end justify-between"><div><p className="eyebrow mb-2">Synthetic workflow library</p><h2 className="text-2xl font-bold tracking-tight">Start with an executable specification</h2></div><span className="hidden text-sm text-[#71807c] md:block">Loaded directly from the CareFlow engine</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{EXAMPLE_PROGRAMS.map((example,index)=><Link key={example.id} href={`/studio?example=${example.id}`} className="panel group p-5 text-inherit no-underline transition hover:-translate-y-0.5 hover:border-[#8dc4bb] hover:shadow-md"><div className="mb-8 flex items-start justify-between"><span className="grid h-11 min-w-11 place-items-center rounded-lg bg-[#edf6f4] px-2 font-mono text-sm font-bold text-[#087f72]">{icons[index]}</span><span className="text-[#98aaa5] transition group-hover:translate-x-1 group-hover:text-[#087f72]">→</span></div><h3 className="font-bold">{example.title}</h3><p className="mt-2 text-sm leading-6 text-[#687873]">{example.description}</p><div className="mt-5 border-t border-[#e5ecea] pt-4 text-xs font-bold text-[#087f72]">OPEN IN STUDIO</div></Link>)}</div></section>

    <section className="rounded-xl border border-[#e2c989] bg-[#fffaf0] px-5 py-4 text-sm leading-6 text-[#73551a]"><b>MVP Simulation Environment —</b> This demonstration uses synthetic incidents and contains no patient information. CareFlow coordinates operational workflows and does not provide clinical guidance or control medical-device functions.</section>
  </div>;
}
