import Link from "next/link";
import { EXAMPLE_PROGRAMS, SYNTHETIC_DISCLAIMER } from "@/lib/careflow";

const pipeline = ["Visual Builder","CareFlow DSL","Lexer","Parser","Typed AST","Validator","Stateful Interpreter","Execution Trace"];
const icons = ["O₂","♥","LAB","DEV"];

export default function Overview() {
  return <div className="mx-auto max-w-[1500px] px-5 py-10 lg:px-8 lg:py-14">
    <section className="grid gap-10 border-b border-[#dce5e2] pb-12 lg:grid-cols-[1.2fr_.8fr] lg:items-center">
      <div><p className="eyebrow mb-4">Clinical workflow engineering environment</p><h1 className="max-w-3xl text-4xl font-bold leading-[1.08] tracking-[-.035em] text-[#14211f] lg:text-6xl">Design clinical logic.<br/><span className="text-[#087f72]">Validate it. Simulate it.</span><br/>Audit every decision.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#5d6d69]">CareFlow is a domain-specific language and simulation environment for expressing healthcare monitoring and escalation workflows as readable, executable specifications.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/studio" className="rounded-lg bg-[#087f72] px-5 py-3 text-sm font-bold text-white no-underline hover:bg-[#076a60]">Open Workflow Studio →</Link><Link href="/language" className="rounded-lg border border-[#cdd9d6] bg-white px-5 py-3 text-sm font-bold text-[#263633] no-underline hover:border-[#87bdb4]">Explore the language</Link></div></div>
      <div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-[#dce5e2] px-5 py-3"><span className="text-xs font-bold uppercase tracking-wider text-[#64736f]">Compiler pipeline</span><span className="rounded-full bg-[#e7f5f2] px-2.5 py-1 text-[10px] font-bold text-[#087f72]">REAL ENGINE</span></div><div className="p-5">{pipeline.map((item,index)=><div key={item} className="flex flex-col items-center"><div className={`w-full rounded-lg border px-4 py-2.5 text-center text-sm font-bold ${index===1?"border-[#72bcb0] bg-[#e7f5f2] text-[#076a60]":index>4?"border-[#bfd1e1] bg-[#f3f7fb] text-[#285b8b]":"border-[#dce5e2] bg-[#fafcfb] text-[#344541]"}`}>{item}</div>{index<pipeline.length-1&&<span className="py-1 text-[#8ba09b]">↓</span>}</div>)}</div></div>
    </section>

    <section className="py-12"><div className="mb-6 flex items-end justify-between"><div><p className="eyebrow mb-2">Synthetic workflow library</p><h2 className="text-2xl font-bold tracking-tight">Start with an executable specification</h2></div><span className="hidden text-sm text-[#71807c] md:block">Loaded directly from the CareFlow engine</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{EXAMPLE_PROGRAMS.map((example,index)=><Link key={example.id} href={`/studio?example=${example.id}`} className="panel group p-5 text-inherit no-underline transition hover:-translate-y-0.5 hover:border-[#8dc4bb] hover:shadow-md"><div className="mb-8 flex items-start justify-between"><span className="grid h-11 min-w-11 place-items-center rounded-lg bg-[#edf6f4] px-2 font-mono text-sm font-bold text-[#087f72]">{icons[index]}</span><span className="text-[#98aaa5] transition group-hover:translate-x-1 group-hover:text-[#087f72]">→</span></div><h3 className="font-bold">{example.title}</h3><p className="mt-2 text-sm leading-6 text-[#687873]">{example.description}</p><div className="mt-5 border-t border-[#e5ecea] pt-4 text-xs font-bold text-[#087f72]">OPEN IN STUDIO</div></Link>)}</div></section>

    <section className="rounded-xl border border-[#e2c989] bg-[#fffaf0] px-5 py-4 text-sm text-[#73551a]"><b className="mr-2">Synthetic demonstration — not clinical guidance.</b>{SYNTHETIC_DISCLAIMER} CareFlow is a hackathon prototype, not a medical device.</section>
  </div>;
}
