"use client";

import { useEffect, useMemo, useState } from "react";
import { EXAMPLE_PROGRAMS, parse, simulate, type SimulationEvent, type SimulationStepInput } from "@/lib/careflow";
import { RuntimeChart, deriveRuntimeMarkers, formatDuration, formatTime } from "./runtime-visualization";

interface Scenario { id:string; title:string; exampleId:string; description:string; steps:SimulationStepInput[]; }
const base={oxygen:97,heart_rate:78,blood_pressure:118,temperature:37,potassium:4.2,lactate:1.3,ventilator_pressure:22,infusion_rate:80,battery_percent:84,connectivity_status:1};
const scenarios:Scenario[]=[
  {id:"stable",title:"Stable Patient",exampleId:"respiratory_monitor",description:"Synthetic readings remain outside rule conditions.",steps:[0,10_000,40_000,160_000].map((timeMs)=>({timeMs,patient:{...base}}))},
  {id:"oxygen",title:"Gradual Oxygen Drop",exampleId:"respiratory_monitor",description:"Normal → threshold crossed → 30s persistence → alert → acknowledgement or escalation.",steps:[{timeMs:0,patient:{...base,oxygen:97}},{timeMs:10_000,patient:{...base,oxygen:91}},{timeMs:20_000,patient:{...base,oxygen:91}},{timeMs:40_000,patient:{...base,oxygen:91}},{timeMs:159_999,patient:{...base,oxygen:91}},{timeMs:160_000,patient:{...base,oxygen:91}}]},
  {id:"heart",title:"Heart Rate Spike",exampleId:"cardiac_deterioration",description:"Synthetic heart rate persists through a five-minute temporal boundary.",steps:[{timeMs:0,patient:{...base,heart_rate:125}},{timeMs:60_000,patient:{...base,heart_rate:126}},{timeMs:299_999,patient:{...base,heart_rate:128}},{timeMs:300_000,patient:{...base,heart_rate:128}}]},
  {id:"lab",title:"Critical Lab Scenario",exampleId:"critical_lab_escalation",description:"Synthetic lab values produce an acknowledgement-controlled alert.",steps:[{timeMs:0,patient:{...base,potassium:6.2,lactate:4.2}},{timeMs:299_999,patient:{...base,potassium:6.2,lactate:4.2}},{timeMs:300_000,patient:{...base,potassium:6.2,lactate:4.2}}]},
  {id:"device",title:"ER Ventilator Connectivity Loss",exampleId:"device_alert",description:"A fictional connectivity alert is assigned, misses acknowledgement, and escalates.",steps:[{timeMs:0,patient:{...base,connectivity_status:1}},{timeMs:10_000,patient:{...base,connectivity_status:0}},{timeMs:129_999,patient:{...base,connectivity_status:0}},{timeMs:130_000,patient:{...base,connectivity_status:0}}]},
];

export function SimulatorWorkspace({autoRunVentilator=false}:{autoRunVentilator?:boolean}){
  const [scenarioId,setScenarioId]=useState(autoRunVentilator?"device":"oxygen");
  const [executed,setExecuted]=useState<SimulationStepInput[]>([]);
  const [cursor,setCursor]=useState(0);
  const [playing,setPlaying]=useState(autoRunVentilator);
  const [selected,setSelected]=useState<SimulationEvent|null>(null);
  const scenario=scenarios.find((item)=>item.id===scenarioId)!;
  const source=EXAMPLE_PROGRAMS.find((example)=>example.id===scenario.exampleId)!.source;
  const workflow=useMemo(()=>parse(source),[source]);
  const result=useMemo(()=>executed.length?simulate(workflow,executed):null,[workflow,executed]);
  const patient=result?.final.patient??scenario.steps[0]!.patient;
  const markers=useMemo(()=>result?deriveRuntimeMarkers(result.events):[],[result]);
  const pending=result?.final.rules.filter((rule)=>rule.acknowledgement.status==="pending"&&rule.firingInstanceId)??[];
  const deviceRule=result?.final.rules.find((rule)=>rule.ruleName==="ventilator_connectivity_lost");

  function reset(nextId=scenarioId){setScenarioId(nextId);setExecuted([]);setCursor(0);setPlaying(false);setSelected(null);}
  function step(){
    if(cursor>=scenario.steps.length){setPlaying(false);return;}
    const next=scenario.steps[cursor]!;const last=executed.at(-1)?.timeMs??-1;
    setExecuted([...executed,{...next,timeMs:Math.max(next.timeMs,last+1)}]);setCursor(cursor+1);
  }
  function acknowledge(instanceId:string){
    if(!result)return;const last=result.final;
    setExecuted([...executed,{timeMs:last.timeMs+1,patient:{...last.patient},acknowledge:[instanceId]}]);
  }
  function startOxygenDemo(){reset("oxygen");setPlaying(true);}
  function startVentilatorDemo(){reset("device");setPlaying(true);}
  function injectTestAlert(){setScenarioId("device");setExecuted(scenarios.find((item)=>item.id==="device")!.steps.slice(0,2));setCursor(2);setPlaying(false);setSelected(null);}
  useEffect(()=>{if(!playing)return;const timer=setTimeout(step,1050);return()=>clearTimeout(timer);});

  return <div className="mx-auto max-w-[1760px] px-4 py-6 lg:px-6">
    <div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-2">Synthetic workflow simulator</p><h1 className="text-2xl font-bold tracking-tight">See operational escalation unfold</h1><p className="mt-1 text-sm text-[#687873]">Signals, markers, actions, and state transitions are rendered from CareFlow runtime output.</p></div><div className="flex flex-wrap gap-2"><button onClick={startVentilatorDemo} className="rounded-lg bg-[#087f72] px-4 py-2 text-sm font-bold text-white hover:bg-[#076a60]">▶ Run ER Ventilator Demo</button><button onClick={injectTestAlert} className="rounded-lg border border-[#6ea99f] bg-white px-4 py-2 text-sm font-bold text-[#076a60]">Inject Test Alert</button><button onClick={startOxygenDemo} className="rounded-lg border border-[#ccd8d5] bg-white px-4 py-2 text-sm font-bold text-[#40514d]">Run oxygen demo</button><button onClick={()=>reset()} className="rounded-lg border border-[#ccd8d5] bg-white px-4 py-2 text-sm font-bold">Reset</button><button onClick={step} disabled={cursor>=scenario.steps.length} className="rounded-lg border border-[#9ac8c0] bg-[#edf8f6] px-4 py-2 text-sm font-bold text-[#076a60] disabled:opacity-40">Step</button><button onClick={()=>setPlaying(!playing)} disabled={cursor>=scenario.steps.length} className="rounded-lg bg-[#263633] px-4 py-2 text-sm font-bold text-white disabled:opacity-40">{playing?"Pause":"Play"}</button></div></div>

    <div className="desktop-grid grid gap-4 lg:grid-cols-[290px_1fr]"><aside className="panel overflow-hidden"><Head title="Test scenarios" label="SYNTHETIC"/><div className="space-y-1 p-2">{scenarios.map((item)=><button key={item.id} onClick={()=>reset(item.id)} className={`w-full rounded-lg p-3 text-left transition ${item.id===scenarioId?"bg-[#e7f5f2] text-[#076a60]":"hover:bg-[#f4f7f6]"}`}><b className="block text-sm">{item.title}</b><span className="mt-1 block text-xs leading-5 text-[#71807c]">{item.description}</span></button>)}</div><div className="border-t border-[#dce5e2] p-4"><span className="eyebrow">Active workflow</span><b className="mt-2 block font-mono text-xs">{workflow.name.name}</b><span className="mt-1 block text-xs text-[#71807c]">{workflow.rules.length} executable rules · parsed AST</span></div></aside>
      <div className="space-y-4">{scenarioId==="device"&&<ScenarioSummary rule={deviceRule}/>}<section className="panel overflow-hidden"><Head title="Synthetic monitor" label={result?formatTime(result.final.timeMs):"NOT STARTED"}/>{scenarioId==="device"?<div className="grid gap-px bg-[#dce5e2] sm:grid-cols-2"><Vital label="Connectivity" value={patient.connectivity_status===0?"Lost":"Connected"} unit=""/><Vital label="Event source" value="Synthetic device gateway" unit=""/></div>:<><div className="grid grid-cols-2 gap-px bg-[#dce5e2] md:grid-cols-4"><Vital label="Oxygen" value={patient.oxygen} unit="%"/><Vital label="Heart Rate" value={patient.heart_rate} unit="bpm"/><Vital label="Blood Pressure" value={patient.blood_pressure} unit="mmHg"/><Vital label="Temperature" value={patient.temperature} unit="°C"/></div><div className="flex flex-wrap gap-2 border-t border-[#dce5e2] bg-[#f8faf9] px-4 py-3">{Object.entries(patient).filter(([key])=>!["oxygen","heart_rate","blood_pressure","temperature"].includes(key)).map(([key,value])=><span key={key} className="rounded-full border border-[#d5dfdd] bg-white px-3 py-1 text-xs"><span className="text-[#71807c]">{key.replaceAll("_"," ")}</span> <b>{value}</b></span>)}</div></>}</section>
        {scenarioId==="device"&&<VentilatorProgress markerKinds={new Set(markers.map((marker)=>marker.kind))} started={executed.length>0}/>}
        {scenarioId==="oxygen"&&<DemoProgress markerKinds={new Set(markers.map((marker)=>marker.kind))} started={executed.length>0}/>} 
        {pending.length>0&&<section className="rounded-xl border border-[#d5bb72] bg-[#fff9e9] p-4 shadow-[0_8px_24px_rgb(126_91_16_/_8%)]"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="eyebrow text-[#856116]">Runtime action required</span><h3 className="mt-1 font-bold">{pending.length} acknowledgement{pending.length===1?"":"s"} pending</h3><p className="mt-1 text-xs text-[#735f32]">Acknowledge now, or continue stepping to demonstrate the real timeout escalation path.</p></div><div className="flex flex-wrap gap-2">{pending.map((rule)=><button key={rule.firingInstanceId} onClick={()=>acknowledge(rule.firingInstanceId!)} className="rounded-lg bg-[#9a6b0e] px-4 py-2.5 text-xs font-bold text-white hover:bg-[#7e570b]">Acknowledge alert · {rule.firingInstanceId}</button>)}</div></div></section>}
      </div></div>

    <div className="mt-4">{result?<RuntimeChart result={result} workflow={workflow} onSelect={setSelected}/>:<EmptyVisualization/>}</div>
    <RuntimeTimeline result={result} selected={selected} onSelect={setSelected}/>
    <div className="mt-4 rounded-lg border border-[#e2c989] bg-[#fffaf0] px-4 py-3 text-xs leading-5 text-[#73551a]"><b>MVP Simulation Environment —</b> This demonstration uses synthetic incidents and contains no patient information. CareFlow coordinates operational workflows and does not provide clinical guidance or control medical-device functions.</div>
  </div>;
}

function RuntimeTimeline({result,selected,onSelect}:{result:ReturnType<typeof simulate>|null;selected:SimulationEvent|null;onSelect:(event:SimulationEvent)=>void}){
  if(!result)return <section className="panel mt-4 overflow-hidden"><Head title="Execution timeline" label="AWAITING FIRST STEP"/><div className="grid h-48 place-items-center text-sm text-[#84938f]">Press Step, Play, or Run oxygen demo to begin deterministic simulation.</div></section>;
  const markers=deriveRuntimeMarkers(result.events);
  const previousByRule=new Map<string,SimulationEvent>();
  return <section className="panel mt-4 overflow-hidden"><Head title="Execution timeline" label={`${result.events.length} OBSERVATIONS · ${markers.length} SEMANTIC EVENTS`}/><div className="desktop-grid grid lg:grid-cols-[1fr_380px]"><div className="code-scroll max-h-[620px] overflow-y-auto p-4"><div className="relative ml-3 border-l border-[#c9d8d4] pl-6">{result.events.map((event,index)=>{const previous=previousByRule.get(event.ruleName);previousByRule.set(event.ruleName,event);const eventMarkers=markers.filter((marker)=>marker.event===event);const active=selected===event;return <button key={`${event.timestamp}-${event.ruleName}-${index}`} onClick={()=>onSelect(event)} className={`relative mb-3 block w-full rounded-xl border p-3 text-left transition ${active?"border-[#58a89a] bg-[#f0faf8] shadow-sm":"border-[#dce5e2] bg-white hover:border-[#7db8ae] hover:bg-[#f8fcfb]"}`}><span className={`absolute -left-[31px] top-4 h-3 w-3 rounded-full border-2 border-white ${event.conditionStatus==="satisfied"?"bg-[#087f72]":event.conditionStatus==="waiting"?"bg-[#d7942d]":event.conditionStatus==="unknown"?"bg-[#b53b3b]":"bg-[#9aaba7]"}`}/><div className="flex flex-wrap items-center gap-2"><b className="font-mono text-xs text-[#087f72]">{formatTime(event.timestamp)}</b><span className="text-xs font-bold">{event.ruleName}</span><Status value={event.conditionStatus}/>{event.firingInstanceId&&<span className="rounded bg-[#edf3f7] px-2 py-0.5 font-mono text-[10px] text-[#3f617d]">{event.firingInstanceId}</span>}</div>{eventMarkers.length>0?<div className="mt-2 flex flex-wrap gap-1.5">{eventMarkers.map((marker)=><span key={marker.id} className="rounded-md border border-[#d6e1df] bg-[#f8faf9] px-2 py-1 text-[10px] font-bold text-[#40514d]">{marker.label}</span>)}</div>:<p className="mt-2 text-xs font-semibold text-[#4f615c]">{observationTitle(event,previous)}</p>}<p className="mt-2 text-xs text-[#657570]">Observed <b>{event.observedValue??"unknown"}</b>{event.durationRequirement&&<> · persisted {formatDuration(event.elapsedDurationMs)} / {formatDuration(event.durationRequirement.milliseconds)}</>}</p>{event.actions.length>0&&<div className="mt-2 flex flex-wrap gap-1">{event.actions.map((action,actionIndex)=><span key={actionIndex} className={`rounded px-2 py-1 text-[10px] font-bold ${action.reason==="acknowledgement_timeout"?"bg-[#fff0f0] text-[#ad3535]":"bg-[#eaf3fb] text-[#285b8b]"}`}>{action.kind.toUpperCase()} {action.target} · {action.reason.replaceAll("_"," ")}</span>)}</div>}</button>;})}</div></div><EventInspector event={selected??result.events.at(-1)!} markers={markers.filter((marker)=>marker.event===(selected??result.events.at(-1)!))}/></div></section>;
}

function DemoProgress({markerKinds,started}:{markerKinds:Set<string>;started:boolean}){
  const stages=[{label:"Normal reading",done:started},{label:"Threshold crossed",done:markerKinds.has("condition_true")},{label:"30s persistence",done:markerKinds.has("persistence_satisfied")},{label:"Nurse alert",done:markerKinds.has("alert_created")},{label:"Ack window",done:markerKinds.has("ack_window")},{label:"Resolved / escalated",done:markerKinds.has("acknowledged")||markerKinds.has("escalated")}];
  return <section className="panel px-4 py-3"><div className="mb-3 flex items-center justify-between"><b className="text-xs">Oxygen demo path</b><span className="text-[10px] font-bold text-[#71807c]">DRIVEN BY RUNTIME MARKERS</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{stages.map((stage,index)=><div key={stage.label} className={`relative rounded-lg border px-2 py-2 text-center text-[10px] font-bold ${stage.done?"border-[#8fc7bd] bg-[#edf8f6] text-[#076a60]":"border-[#dde5e3] bg-[#fafbfb] text-[#8a9995]"}`}><span className="mb-1 block font-mono text-[9px]">{stage.done?"✓":String(index+1).padStart(2,"0")}</span>{stage.label}</div>)}</div></section>;
}
function VentilatorProgress({markerKinds,started}:{markerKinds:Set<string>;started:boolean}){const stages=[{label:"Connectivity checked",done:started},{label:"Test alert injected",done:markerKinds.has("condition_true")},{label:"Assigned to ER Operations",done:markerKinds.has("alert_created")},{label:"Ack deadline active",done:markerKinds.has("ack_window")},{label:"Deadline missed",done:markerKinds.has("deadline_missed")},{label:"Clinical Engineering escalation",done:markerKinds.has("escalated")}];return <section className="panel px-4 py-3" aria-label="Ventilator demo progress"><div className="mb-3 flex items-center justify-between"><b className="text-xs">Ventilator connectivity demo path</b><span className="text-[10px] font-bold text-[#71807c]">DRIVEN BY RUNTIME MARKERS</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{stages.map((stage,index)=><div key={stage.label} className={`rounded-lg border px-2 py-2 text-center text-[10px] font-bold ${stage.done?"border-[#8fc7bd] bg-[#edf8f6] text-[#076a60]":"border-[#dde5e3] bg-[#fafbfb] text-[#8a9995]"}`}><span className="mb-1 block font-mono text-[9px]">{stage.done?"✓":String(index+1).padStart(2,"0")}</span>{stage.label}</div>)}</div></section>;}

function EventInspector({event,markers}:{event:SimulationEvent;markers:ReturnType<typeof deriveRuntimeMarkers>}){
  return <aside className="border-l border-[#dce5e2] bg-[#f8faf9] p-5"><span className="eyebrow">Event inspector</span><h3 className="mt-2 font-bold">{event.ruleName}</h3>{markers.length>0&&<div className="mt-3 space-y-2">{markers.map((marker)=><div key={marker.id} className="rounded-lg border border-[#dce5e2] bg-white p-2.5"><b className="block text-xs">{marker.label}</b><p className="mt-1 text-[11px] leading-4 text-[#687873]">{marker.detail}</p></div>)}</div>}<dl className="mt-4 space-y-3 text-xs">{[["Timestamp",formatTime(event.timestamp)],["Condition",event.conditionStatus],["Observed value",event.observedValue??"Unknown"],["Elapsed",formatDuration(event.elapsedDurationMs)],["Duration required",event.durationRequirement?formatDuration(event.durationRequirement.milliseconds):"Immediate"],["Firing instance",event.firingInstanceId??"Not fired"],["Acknowledgement",event.acknowledgementStatus],["Escalation",event.escalationStatus.triggered?`Triggered → ${event.escalationStatus.target}`:event.escalationStatus.pending?"Awaiting acknowledgement":"Not triggered"]].map(([key,value])=><div key={key as string} className="flex justify-between gap-4 border-b border-[#dde6e3] pb-2"><dt className="text-[#71807c]">{key}</dt><dd className="text-right font-semibold">{value}</dd></div>)}</dl>{event.actions.length>0&&<div className="mt-4"><span className="eyebrow">Actions emitted</span>{event.actions.map((action,index)=><div key={index} className="mt-2 rounded-lg bg-white p-2 text-xs"><b>{action.kind.toUpperCase()} {action.target}</b><span className="mt-1 block text-[10px] text-[#71807c]">{action.reason.replaceAll("_"," ")} · {action.firingInstanceId}</span></div>)}</div>}</aside>;
}

function observationTitle(event:SimulationEvent,previous?:SimulationEvent){if(event.conditionStatus==="waiting")return event.elapsedDurationMs===0?"Condition true · timer beginning":"Condition remains true · timer accumulating";if(event.conditionStatus==="satisfied")return previous?.conditionStatus==="satisfied"?"Condition remains satisfied · repeat firing suppressed":"Condition satisfied";if(event.conditionStatus==="unknown")return"Reading unknown · timer reset";return"Condition false · timer reset";}
function EmptyVisualization(){return <section className="panel overflow-hidden"><Head title="Runtime signal analysis" label="REAL SIMULATION OUTPUT"/><div className="grid h-64 place-items-center bg-[#fbfcfc] px-6 text-center"><div><div className="mx-auto mb-3 grid h-12 w-12 place-items-center rounded-full bg-[#e7f5f2] text-xl text-[#087f72]">⌁</div><b className="text-sm">No runtime observations yet</b><p className="mt-1 text-xs text-[#71807c]">Execute a step to plot synthetic signals and CareFlow event markers.</p></div></div></section>;}
function ScenarioSummary({rule}:{rule:ReturnType<typeof simulate>["final"]["rules"][number]|undefined}){const ack=rule?.acknowledgement.status??"Not started";const escalated=rule?.escalation.triggered===true;const owner=escalated?"Clinical Engineering":rule?.firingInstanceId?"ER Operations":"Unassigned";const items=[["Device ID","VENT-SIM-042"],["Location","Fictional ER · Bay S-04"],["Current owner",owner],["Acknowledgement",ack.replaceAll("_"," ")],["Escalation",escalated?"Escalated":"Not escalated"],["Data status","Synthetic only"]];return <section className="panel overflow-hidden" aria-label="Scenario information"><Head title="ER Ventilator Connectivity Loss" label="OPERATIONAL INCIDENT"/><dl className="grid gap-px bg-[#dce5e2] sm:grid-cols-2 xl:grid-cols-3">{items.map(([label,value])=><div key={label} className="bg-white p-4"><dt className="text-[10px] font-bold uppercase tracking-wider text-[#71807c]">{label}</dt><dd className="mt-1.5 text-sm font-bold capitalize">{value}</dd></div>)}</dl><p className="border-t border-[#dce5e2] bg-[#f8faf9] px-4 py-3 text-xs leading-5 text-[#5d6d69]">Device connectivity loss may be operational, technical, or security-related. CareFlow follows the hospital&apos;s approved routing policy; it does not classify every connectivity loss as a cyberattack.</p></section>;}
function Head({title,label}:{title:string;label:string}){return <div className="flex items-center justify-between border-b border-[#dce5e2] px-4 py-3"><b className="text-sm">{title}</b><span className="text-[10px] font-bold tracking-wider text-[#71807c]">{label}</span></div>;}
function Vital({label,value,unit}:{label:string;value?:number|string;unit:string}){return <div className="bg-[#101b19] p-5 text-white"><span className="text-[10px] font-bold uppercase tracking-widest text-[#8da39e]">{label}</span><div className="mt-2 font-mono text-3xl font-bold text-[#78e1cd]">{value??"—"}<span className="ml-1 text-xs font-normal text-[#8da39e]">{unit}</span></div></div>;}
function Status({value}:{value:string}){const color=value==="satisfied"?"bg-[#e7f5f2] text-[#076a60]":value==="waiting"?"bg-[#fff5dc] text-[#8b620e]":value==="unknown"?"bg-[#fff0f0] text-[#a83333]":"bg-[#eff3f2] text-[#61706c]";return <span className={`rounded px-2 py-0.5 text-[10px] font-bold uppercase ${color}`}>{value}</span>;}
